#!/usr/bin/env sh

temp_dir="$(mktemp -d)"
trap 'rm -rf -- "$temp_dir"' INT TERM HUP EXIT
reordered_file="${temp_dir}/reordered"
blackened_file="${temp_dir}/blackened"

curl --silent -XPOST "http://localhost:31338$(pwd)" --data-binary @- > "$reordered_file"

if ! curl --fail --silent -XPOST http://localhost:31337 --data-binary @- <"$reordered_file" > "$blackened_file"; then
   cat "$reordered_file"
else
   if [ -s "$blackened_file" ]; then
       cat "$blackened_file"
   else
       cat "$reordered_file"
   fi
fi

